%   function createfigure(PSNRs1,imagename, stego_image, T_number)
function createfigure(PSNRs1,PSNRs2,PSNRs3,PSNRs4,PSNRs5,PSNRs6,PSNRs7, PSNRs8,PSNRs9, PSNRs10, PSNRs11,imagename, stego_image, T_number, max_point)
 
%CREATEFIGURE(X1,Y1,X2,Y2,X3,Y3,X4,Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 05-Jun-2014 16:25:46

% Create figure
figure1 = figure;
set(figure1, 'Position', [1 1 1900 1000]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'0','0.6','1.2','1.8','2.4','3.0', '3.6', '4.2', '4.8','5.4', '6.0'},...
    'XTick',[0 0.6 1.2 1.8 2.4 3.0 3.6 4.2 4.8 5.4 6.0],...
    'XGrid','on',...
    'FontSize',14);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 5.6]);
xlim(axes1,[0 max_point]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(PSNRs1(:,1),PSNRs1(:,2),'Parent',axes1,'MarkerSize',8,'Marker','h','LineWidth',1,...
    'Color',[1 0 0],...
    'DisplayName','Lu2016(T=3)');

plot(PSNRs7(:,1),PSNRs7(:,2),'Parent',axes1,'MarkerSize',8,'Marker','pentagram','LineWidth',1,...
    'Color',[0 1 0],...
    'DisplayName','Lu2016(T=4)');
% 
% % Create plot
plot(PSNRs2(:,1),PSNRs2(:,2),'Parent',axes1,'MarkerSize',8,'Marker','^','LineWidth',1,...
    'Color',[0 0 1],...
    'DisplayName','Lu2015');
% 
plot(PSNRs3(:,1),PSNRs3(:,2),'Parent',axes1,'MarkerSize',8,'Marker','square','LineWidth',1,...
    'DisplayName','NonFolding',...
    'Color',[0 0.600000023841858 0.600000023841858]);

plot(PSNRs4(:,1),PSNRs4(:,2),'Parent',axes1,'MarkerSize',8,'Marker','x','LineWidth',1,...
    'DisplayName','Lee2009',...
    'Color',[0.48 0.06 0.89]);
% 
% % Create plot
plot(PSNRs5(:,1),PSNRs5(:,2),'Parent',axes1,'MarkerSize',8,'Marker','diamond','LineWidth',1,...
    'Color',[0.749019622802734 0 0.749019622802734],...
    'DisplayName','Lee2013');
% 
plot(PSNRs6(:,1),PSNRs6(:,2),'Parent',axes1,'MarkerSize',8,'Marker','.','LineWidth',1,...
    'Color',[0.65 0.54 0.12],...
    'DisplayName','Chang2013');
%  
plot(PSNRs8(:,1),PSNRs8(:,2),'Parent',axes1,'MarkerSize',8,'Marker','+','LineWidth',1,...
    'Color',[0.11 0.54 0.12],...
    'DisplayName','fivePixelReEncde(T=3)');
%  
plot(PSNRs9(:,1),PSNRs9(:,2),'Parent',axes1,'MarkerSize',8,'Marker','<','LineWidth',1,...
    'Color',[0.65 0.11 0.12],...
    'DisplayName','fivePixel(T=3)');
% 
%  
plot(PSNRs10(:,1),PSNRs10(:,2),'Parent',axes1,'MarkerSize',8,'Marker','*','LineWidth',1,...
    'Color',[0.65 0.11 0.11],...
    'DisplayName','fivePixelReEncde(T=4)');

%  
plot(PSNRs11(:,1),PSNRs11(:,2),'Parent',axes1,'MarkerSize',8,'Marker','o','LineWidth',1,...
    'Color',[0.44 0.54 0.44],...
    'DisplayName','fivePixel(T=4)');

% Create xlabel
xlabel('Payload(bpp)','FontWeight','bold','FontSize',24,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('PSNR(dB)','FontWeight','bold','FontSize',24,...
    'FontName','Times New Roman');

% Create title
tt = [stego_image ' => ' imagename]
title(tt,'FontWeight','bold','FontSize',24,...
    'FontName','Times New Roman');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',18,'FontName','Times New Roman', 'Location','EastOutside');

 saveas(figure1,['experimental results\' imagename '_' stego_image '_T_' num2str(T_number) '.fig'],'fig');
saveas(figure1,['experimental results\' imagename '_' stego_image '_T_' num2str(T_number) '.jpg'],'jpg');


